name: Github Action Workflow

on:
    push:
        branches:
            - main

jobs:
    build-push:
        name: Test the application and build image and push to Docker Hub
        runs-on: ubuntu-latest
        steps:
           - name: checkout code
             uses: actions/checkout@v2

           - name: set up Java environment
             uses: actions/setup-java@v5
             with:
                distribution: 'corretto' # See 'Supported distributions' for available options
                java-version: '21'

           - name: Run unit tests
             run: mvn -B test --file pom.xml

           - name: Build the appplication
             run: |
                mvn clean
                mvn -B package --file pom.xml

           - name: Login to Docker Hub
             uses: docker/login-action@v3
             with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

           - name: Build and push to Docker
             uses: docker/build-push-action@v6
             with:
               context: .
               push: true
               tags: ${{ vars.DOCKERHUB_USERNAME }}/springbootapp:latest
